version: '3'
services:
  datadog:
    image: 'datadog/agent:7.31.1'
    environment:
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.team":"team"}
      - DD_TAGS='env:dd101-dev'
      - DD_APM_NON_LOCAL_TRAFFIC=true
    ports:
      - 127.0.0.1:8126:8126/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
      - DD_AGENT_HOST=datadog
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_SERVICE=discounts-service
      - DD_VERSION=2.1.2
      - DD_ENV=dd101-dev
    image: 'ddtraining/discounts:2.1.2'
    command:
      [
        sh,
        -c,
        'pip install ddtrace -U && ddtrace-run flask run --port=5001 --host=0.0.0.0',
      ]
    ports:
      - '5001:5001'
    depends_on:
      - datadog
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "discounts-service"}]'
      com.datadoghq.tags.service: 'discounts-service'
      com.datadoghq.tags.env: 'dd101-dev'
  frontend:
    environment:
      - DD_AGENT_HOST=datadog
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DB_USERNAME
      - DB_PASSWORD
      - DD_CLIENT_TOKEN
      - DD_APPLICATION_ID
      - DD_SERVICE=store-frontend
      - DD_VERSION=2.1.2
      - DD_ENV=dd101-dev
    image: 'ddtraining/storefront-fixed:2.1.2'
    command: sh docker-entrypoint.sh
    ports:
      - '3000:3000'
    depends_on:
      - datadog
      - db
      - discounts
      - advertisements
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "store-frontend"}]'
      com.datadoghq.tags.service: 'store-frontend'
      com.datadoghq.tags.env: 'dd101-dev'
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
      - DD_AGENT_HOST=datadog
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_SERVICE=advertisements-service
      - DD_VERSION=2.1.2
      - DD_ENV=dd101-dev
    image: 'ddtraining/advertisements-fixed:2.1.2'
    command:
      [
        sh,
        -c,
        'pip install ddtrace -U && ddtrace-run flask run --port=5002 --host=0.0.0.0',
      ]
    ports:
      - '5002:5002'
    depends_on:
      - datadog
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "advertisements-service"}]'
      com.datadoghq.tags.service: 'advertisements-service'
      com.datadoghq.tags.env: 'dd101-dev'
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - '5432:5432'
    labels:
      com.datadoghq.tags.env: 'dd101-dev'
      com.datadoghq.tags.service: 'database'
      com.datadoghq.tags.version: '11.12'
      my.custom.label.team: 'database'
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":5432,"username":"datadog","password":"datadog"}]'
      com.datadoghq.ad.logs: '[{"source": "postgresql", "service": "database"}]'
    volumes:
      - /root/postgres:/var/lib/postgresql/data
      - /root/dd_agent.sql:/docker-entrypoint-initdb.d/dd_agent.sql
